# This spec file was generated by KDevelop
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: klininfo
Version: 0.2
Release: 1
Vendor: Paulius Danenas
Copyright: GPL
Group: Applications/System
Packager: Paulius Danenas
BuildRoot: %{_tmppath}/%{name}-root
Source: klininfo-0.2.tar.gz
Summary: Linux information utility

%description
This a Linux information utility, that gives information about packages, memory, disk usage, processes, running on this system and etc. You can also use this program as a "notebook" for describing Linux commands, system and log files, use the script to retrieve all the information you need  

%prep
%setup
CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" ./configure \
--target=i686

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
/usr/share/applnk/Utilities/*
%{_bindir}/*
/usr/share/doc/HTML/en/klininfo/*
/usr/share/doc/HTML/en/klininfo/common/*
%{_datadir}/apps/%{name}/*
# %{_datadir}/apps/%{name}/icons/*
# %{_datadir}/apps/%{name}/pixmaps/*
# %{_datadir}/apps/%{name}/templates/*
# %{_datadir}/apps/%{name}/translations/*
/usr/share/icons/hicolor/16x16/apps/*
/usr/share/icons/hicolor/32x32/apps/*
/usr/share/locale/*
%changelog

